### ISSUE TITLE
Crashes on publish

### ISSUE THREAD

**Issue by ToniIltanen** [jenkinsci/brakeman-plugin#10]
the brakeman plugin crashes when publishing:

**output from jenkins project build**

+ brakeman -o brakeman-output.tabs --no-progress --separate-models
Loading scanner...
Processing application in [path]
Processing gems...
[Notice] Detected Rails 4 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
Processing initializers...
Processing libs...
Processing routes...          
Processing templates...       
Processing data flow in templates...
Processing models...          
Processing controllers...     
Processing data flow in controllers...
Indexing call sites...        
Running checks in parallel...
 - CheckBasicAuth
 - CheckBasicAuthTimingAttack
 - CheckCrossSiteScripting
 - CheckContentTag
 - CheckCreateWith
 - CheckDefaultRoutes
 - CheckDeserialize
 - CheckDetailedExceptions
 - CheckDigestDoS
 - CheckDynamicFinders
 - CheckEscapeFunction
 - CheckEvaluation
 - CheckExecute
 - CheckFileAccess
 - CheckFileDisclosure
 - CheckFilterSkipping
 - CheckForgerySetting
 - CheckHeaderDoS
 - CheckI18nXSS
 - CheckJRubyXML
 - CheckJSONEncoding
 - CheckJSONParsing
 - CheckLinkTo
 - CheckLinkToHref
 - CheckMailTo
 - CheckMassAssignment
 - CheckMimeTypeDoS
 - CheckModelAttrAccessible
 - CheckModelAttributes
 - CheckModelSerialize
 - CheckNestedAttributes
 - CheckNestedAttributesBypass
 - CheckNumberToCurrency
 - CheckQuoteTableName
 - CheckRedirect
 - CheckRegexDoS
 - CheckRender
 - CheckRenderDoS
 - CheckRenderInline
 - CheckResponseSplitting
 - CheckRouteDoS
 - CheckSafeBufferManipulation
 - CheckSanitizeMethods
 - CheckSelectTag
 - CheckSelectVulnerability
 - CheckSend
 - CheckSendFile
 - CheckSessionManipulation
 - CheckSessionSettings
 - CheckSimpleFormat
 - CheckSingleQuotes
 - CheckSkipBeforeFilter
 - CheckSQL
 - CheckSQLCVEs
 - CheckSSLVerify
 - CheckStripTags
 - CheckSymbolDoSCVE
 - CheckTranslateBug
 - CheckUnsafeReflection
 - CheckValidationRegex
 - CheckWithoutProtection
 - CheckXMLDoS
 - CheckYAMLParsing
Checks finished, collecting results...
Generating report...
Report saved in 'brakeman-output.tabs'
ERROR: Step ‘Publish Brakeman warnings’ aborted due to exception: 
java.lang.NoClassDefFoundError: Could not initialize class hudson.plugins.analysis.util.EncodingValidator
	at hudson.plugins.analysis.core.HealthAwareRecorder.copyFilesWithAnnotationsToBuildFolder(HealthAwareRecorder.java:333)
	at hudson.plugins.analysis.core.HealthAwarePublisher.perform(HealthAwarePublisher.java:89)
	at hudson.plugins.analysis.core.HealthAwareRecorder.perform(HealthAwareRecorder.java:280)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
An attempt to send an e-mail to empty list of recipients, ignored.
Finished: FAILURE

**Comment by ConstantineXVI** [comment]
Need to know your platform and versions of Jenkins, analysis-core, and this plugin.

**Comment by ToniIltanen** [comment]
OS Debian 7
Jenkins is the newest version from http://pkg.jenkins-ci.org/debian/
Brakeman gem added today to project (Rails 4.2.6)
Brakeman plugin added today through jenkins

**System Properties**

Name  ↓
Value   
awt.toolkit	sun.awt.X11.XToolkit
executable-war	/usr/share/jenkins/jenkins.war
file.encoding	UTF-8
file.encoding.pkg	sun.io
file.separator	/
hudson.diyChunking	true
java.awt.graphicsenv	sun.awt.X11GraphicsEnvironment
java.awt.headless	true
java.awt.printerjob	sun.print.PSPrinterJob
java.class.path	/usr/share/jenkins/jenkins.war
java.class.version	51.0
java.endorsed.dirs	/usr/lib/jvm/java-7-openjdk-i386/jre/lib/endorsed
java.ext.dirs	/usr/lib/jvm/java-7-openjdk-i386/jre/lib/ext:/usr/java/packages/lib/ext
java.home	/usr/lib/jvm/java-7-openjdk-i386/jre
java.io.tmpdir	/tmp
java.library.path	/usr/java/packages/lib/i386:/usr/lib/i386-linux-gnu/jni:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/lib/jni:/lib:/usr/lib
java.net.preferIPv4Stack	true
java.runtime.name	OpenJDK Runtime Environment
java.runtime.version	1.7.0_111-b01
java.specification.name	Java Platform API Specification
java.specification.vendor	Oracle Corporation
java.specification.version	1.7
java.vendor	Oracle Corporation
java.vendor.url	http://java.oracle.com/
java.vendor.url.bug	http://bugreport.sun.com/bugreport/
java.version	1.7.0_111
java.vm.info	mixed mode, sharing
java.vm.name	OpenJDK Client VM
java.vm.specification.name	Java Virtual Machine Specification
java.vm.specification.vendor	Oracle Corporation
java.vm.specification.version	1.7
java.vm.vendor	Oracle Corporation
java.vm.version	24.111-b01
jna.loaded	true
jna.platform.library.path	/usr/lib/i386-linux-gnu:/lib/i386-linux-gnu:/usr/lib:/lib:/usr/lib/i386-linux-gnu/i686/sse2:/usr/lib/sse2:/lib/i386-linux-gnu/i686/cmov:/usr/lib/i386-linux-gnu/i686/cmov:/usr/lib/i386-linux-gnu/i586:/usr/lib/i386-linux-gnu/sse2
jnidispatch.path	/tmp/jna--1712433994/jna1562073000979613859.tmp
line.separator	
mail.smtp.sendpartial	true
mail.smtps.sendpartial	true
os.arch	i386
os.name	Linux
os.version	3.2.0-4-686-pae
path.separator	:
sun.arch.data.model	32
sun.boot.class.path	/usr/lib/jvm/java-7-openjdk-i386/jre/lib/resources.jar:/usr/lib/jvm/java-7-openjdk-i386/jre/lib/rt.jar:/usr/lib/jvm/java-7-openjdk-i386/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-7-openjdk-i386/jre/lib/jsse.jar:/usr/lib/jvm/java-7-openjdk-i386/jre/lib/jce.jar:/usr/lib/jvm/java-7-openjdk-i386/jre/lib/charsets.jar:/usr/lib/jvm/java-7-openjdk-i386/jre/lib/rhino.jar:/usr/lib/jvm/java-7-openjdk-i386/jre/lib/jfr.jar:/usr/lib/jvm/java-7-openjdk-i386/jre/classes
sun.boot.library.path	/usr/lib/jvm/java-7-openjdk-i386/jre/lib/i386
sun.cpu.endian	little
sun.cpu.isalist	
sun.font.fontmanager	sun.awt.X11FontManager
sun.io.unicode.encoding	UnicodeLittle
sun.java.command	/usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080
sun.java.launcher	SUN_STANDARD
sun.jnu.encoding	UTF-8
sun.management.compiler	HotSpot Client Compiler
sun.os.patch.level	unknown
svnkit.http.methods	Digest,Basic,NTLM,Negotiate
svnkit.ssh2.persistent	false

**Comment by ToniIltanen** [comment]
Problem was fixed by reinstalling the plugin and restarting jenkins. 

More from the error if it helps,
While the build was a failure, the Brakeman vulnerability results could be opened from the build and i could browse the brakeman results. When i clicked the link which would open the file content view (which should open the source code with highlighting), jenkins went to an error page.

**Comment by ConstantineXVI** [comment]
Noted. Please open if you hit a reoccurrence.
