### ISSUE TITLE
Error with null line

### ISSUE THREAD

**Issue by historypeats** [jenkinsci/brakeman-plugin#19]
Hello,

I'm using the brakeman plugin and I seem to keep getting the following:

>  saved in 'brakeman-output.json'
> [BRAKEMAN] JSONObject["line"] is not a number.
> Build step 'Publish Brakeman warnings' changed build result to FAILURE

When looking at the results of brakeman-output.json, it looks like the error stems from the "line" being labeled as "null".

> {
>       "warning_type": "Mass Assignment",
>       "warning_code": 60,
>       "fingerprint": "[REDACTED]",
>       "check_name": "ModelAttrAccessible",
>       "message": "Potentially dangerous attribute available for mass assignment",
>       "file": "[REDACTED]",
>       "line": null,
>       "link": "http://brakemanscanner.org/docs/warning_types/mass_assignment/",
>       "code": "[REDACTED]",
>       "render_path": null,
>       "location": {
>         "type": "[REDACTED]",
>         "model": "[REDACTED]"
>       },
>       "user_input": null,
>       "confidence": "Weak"
>     }

Not sure if this is the cause: https://github.com/jenkinsci/brakeman-plugin/blob/master/src/main/java/hudson/plugins/brakeman/scanners/BrakemanJSONScanner.java#L66-L69

Maybe we can fix this by adding a check for null as well?

Cheers

**Comment by presidentbeef** [comment]
Agree...I will fix.

**Comment by historypeats** [comment]
Awesome, thank you!

**Comment by presidentbeef** [comment]
Version 0.12 of the plugin is now available - please let me know if you still have trouble with null values.
