### ISSUE TITLE
Ignore warnings still show up on charts/graphs and in reports without a way to disable them.

### ISSUE THREAD

**Issue by ThomasOwens** [jenkinsci/brakeman-plugin#21]
We recently switched from tab output to JSON output in brakeman per the recommendation on the plugin page (https://plugins.jenkins.io/brakeman). However, when we did, the graph immediately spiked up. I realized that when viewing the graph or the report, the total number of warnings includes those that are in the ignore file.

This appears to be related to #8 and #9. I like the ability to see the list of ignored warnings in the report summary, but these probably shouldn't show up in the count of all warnings or in the graph. Minimally, there should be an option to disable including all warnings in these outputs.

**Comment by presidentbeef** [comment]
FWIW, I agree. I just have very little energy to dig into Jenkins/Java :grimacing:
