### ISSUE TITLE
analysis-core is end-of-life

### ISSUE THREAD

**Issue by uhafner** [jenkinsci/brakeman-plugin#23]
I'm not sure if you noticed that already: [analysis-core](https://github.com/jenkinsci/analysis-core-plugin) reached end-of-life since spring 2019. In order to archive the `analysis-core` project it is required that you also update your plugin to the successor API of the [Warnings Next Generation Plugin](https://github.com/jenkinsci/warnings-ng-plugin/). Alternatively, you can copy all classes of  `analysis-core` into your plugin (or take over the ownership of the analysis-core plugin). What do you think?

**Comment by presidentbeef** [comment]
I did not know that. Thanks for the heads-up!

I'd prefer updating to the new thing. I will take a look.

**Comment by uhafner** [comment]
Typically a static analysis tool just needs to provide a parser now. Everything else is handled by the warnings plugin.

**Comment by presidentbeef** [comment]
@uhafner is it easier to add a parser (in [here](https://github.com/jenkinsci/analysis-model/tree/master/src/main/java/edu/hm/hafner/analysis/parser)?) or to output JSON with the expected fields?

**Comment by uhafner** [comment]
Since you already have a parser, you can simply convert it so that it will produce `Issue` instances in the `analysis-model` project. Then file a PR in `analysis-model` so we can create a parser descriptor in the warnings plugin (that provides some additional information like URL, help text).

**Comment by daniel-beck** [comment]
Brakeman support exists in [analysis-model 9.0.0 and newer](https://github.com/jenkinsci/analysis-model/releases/tag/v9.0.0), [integrated into Warnings NG 8.4.2](https://github.com/jenkinsci/warnings-ng-plugin/releases/tag/v8.4.2).

**Comment by gdelisle** [comment]
Sorry, where is the fix for this issue? It seems like the code has been fixed months ago and the documentation is updated, but the plugin version in the directory still stands at 0.13, no update has appeared in the update center, and the link to download the .hpi is broken. Is this issue fixed or not, and if so how can I update to the fixed version?

**Comment by presidentbeef** [comment]
The fix is to use https://plugins.jenkins.io/warnings-ng/ instead. This plugin is no longer maintained. Relevant documentation will be updated.
