### ISSUE TITLE
High, Normal, Low misnamed "priority"

### ISSUE THREAD

**Issue by marknadig** [jenkinsci/brakeman-plugin#3]
The "High", "Normal" and "Low" are actually "confidence levels"
http://brakemanscanner.org/docs/confidence/

Labeling them as "priority" mischaracterizes the true nature of the output.

**Comment by presidentbeef** [comment]
Hi Mark,

The "priority" labels are produced by the parent "static analysis plugin" and as far as I know cannot be changed by the Brakeman plugin. However, I don't think they are too misleading. Brakeman's "confidence" levels are really a mixture of confidence and priority.
