### ISSUE TITLE
Can't build plugin.

### ISSUE THREAD

**Issue by gnuchu** [jenkinsci/brakeman-plugin#4]
Having trouble building the plugin. Have tried with Java 7 and Java 8 with maven 2 and 3. On mac and linux. Both fail with the same error:

    [ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:1.67:apt-compile (default-apt-compile) on project brakeman: Execution default-apt-compile of goal org.jenkins-ci.tools:maven-hpi-plugin:1.67:apt-compile failed: A required class was missing while executing org.jenkins-ci.tools:maven-hpi-plugin:1.67:apt-compile: com/sun/mirror/apt/AnnotationProcessorFactory

Any ideas on how to solve?

**Comment by ConstantineXVI** [comment]
I recall running into this trying to update for the latest hpi plugin; couldn't tell you the exact issue but a fresh checkout ought to build on both now (verified with JDK8/mvn3 on OSX and [Arch] Linux, latter of which having a completely pristine JDK environment).
