### ISSUE TITLE
portlets support

### ISSUE THREAD

**Issue by alfredolopez-kantox** [jenkinsci/brakeman-plugin#5]
I have setup a dashboard in Jenkins showing rubocop warnings (using checkstyle format) and I would like to add a chart (portlet) showing the trend of brakeman warnings. Is there any possibility to do that? Right now the only way I can think of to see the brakeman warnings trend is to go inside the Jenkins job itself.

**Comment by alfredolopez-kantox** [comment]
I found a workaround using the iframe portlet :) I'll close the ticket.

**Comment by presidentbeef** [comment]
Sorry, I haven't gotten a chance to look into it yet. Glad you found a workaround for now.
