### ISSUE TITLE
Wrong Reference Build

### ISSUE THREAD

**Issue by fmunozkantox** [jenkinsci/brakeman-plugin#6]
We have a trouble using the brakeman-plugin in our Jenkins.

We have set the options:
"Compute new warnings (based on the last successful build unless another reference build is chosen below)"
and
"Use previous build as reference"

But when the plugin is always selecting the last successful build instead of the last build.

We have tried to reinstall the plugin, but it continues selecting the last successful build instead of the last build.

Versions used:
- Ubuntu 14.04
- Jenkins: 2.2
- brakeman-plugin: 0.7

**Comment by ConstantineXVI** [comment]
Can you give this a go again with 0.8? Haven't explicitly done anything about it, but first want to rule out the old analysis-core plugin 0.7 was using first given the version gap.
