### ISSUE TITLE
Displaying Ignored Warnings

### ISSUE THREAD

**Issue by tmobaird** [jenkinsci/brakeman-plugin#8]
Hey Everyone,

My team has been using this plugin on our Jenkins server for a while, and we think that it would be very useful to have a display for the current ignored brakeman warnings. Very similar to the way the plugin already displays the vulnerabilities. This would be very helpful in seeing all the different warnings that are being ignored, in an easily readable way, since the list can get long in cases.

I think another useful functionality to go along with this could also be a threshold limiting these ignored warnings (ex. > x number of ignored warnings makes the build unstable). I think this could definitely provoke people to fix these security vulnerabilities instead of just marking them as "ignored" when they find them. That being said, a display for the ignored warnings would definitely be the most useful.

I've delved into some of the work that goes into using analysis-core to parse these files (brakeman-output & brakeman.ignore) and add the different warnings that are found. I also found it fairly easy to parse the brakeman.ignore files, and add annotations for them. The problem I found with that, is that the reports are generated from a collection of all these annotations, and do not differentiate from the different objects that you create annotations with. Ex:

`project.addAnnotation(Warning.new(args));`
`project.addAnnotation(IgnoredWarning.new(args));`

I was wondering if there was another way to accomplish this differentiation of information? And/or if this is a feature that you all would be potentially interested in adding?

I am definitely willing to create a PR for this, if you all are open to outside contributions!

Any help would be greatly appreciated! Thanks!

**Comment by presidentbeef** [comment]
I think to do this, the Jenkins plugin will need to switch to consuming the JSON output from Brakeman. (I think that would be a good idea in general, actually.) The JSON reports already include information about which warnings are ignored.

**Comment by tmobaird** [comment]
@presidentbeef I actually just noticed that. Didn't realize that the JSON output file gave you both sets of information. Thanks for the heads up! 

I definitely agree though, using the JSON is probably a better way to go. The JSON report looks pretty straight forward. I can take a crack at making the plugin parse the JSON report (instead of the current brakeman-output.tabs format) if you don't mind!

**Comment by presidentbeef** [comment]
It's up to @ConstantineXVI but I think that would be a great improvement.

**Comment by ConstantineXVI** [comment]
I would gladly accept a PR @tmobaird if you have the bandwidth (as I sadly do not in the short term). The one wrinkle I would add is that there ought to be backwards compatibility; JSON is the better way but there are few forces more deadly than a mob of angry developers that blindly clicked update and found their builds are suddenly broken.

**Comment by tmobaird** [comment]
@ConstantineXVI no worries, I have time available. I can work on this and submit a PR at some point soon!

That's a really good point though. This should definitely be backwards compatible (great description btw, I really don't want to create an angry mob of developers lol). I was thinking that I could include two parsing strategies for this, one that is used when a .tabs file is given, and another that is used when a JSON file is given.

**Comment by ConstantineXVI** [comment]
Mind, I'm not sure offhand if there's any checking against the extension of the input file. Which shouldn't make things particularly more complicated; both formats are predictable enough that the first few bytes are enough context to figure it out.

**Comment by tmobaird** [comment]
@ConstantineXVI yep, sounds good. Thanks for the heads up! I'll get started on this now.

**Comment by tmobaird** [comment]
Just wanted to give an update on this. I have completed the new functionalities for this on my feature branch, and am currently cleaning up the code. I should have a PR up for this before the end of the week.
